const P=[['index','Voorpagina'],['femicide-monitor','Femicide-monitor'],['vrouwen','Expertenzoeker'],['kopcheck','Kopcheck'],['community','Community'],['over','Over ons']];
const V={Solidariteit:'Vrouwen en hun verhalen staan centraal. We verbinden losse gevallen tot een gedeeld verhaal.',Veiligheid:'Zorgvuldige berichtgeving over geweld, met hulpinformatie en zichtbare patronen.',Rechtvaardigheid:'Verantwoordelijkheid ligt bij de dader, nooit bij het slachtoffer. Vrouwen krijgen een eerlijk aandeel als bron.',Empowerment:'Vrouwen als expert, leider en maker. Lezers krijgen taal om geweld te herkennen en te benoemen.'};
const $=s=>document.querySelector(s),page=document.body.dataset.page;
/* Header: klapt in bij scrollen */
const hd=$('#top');hd.className='hd';
const valueId=v=>`waarde-${v.toLowerCase()}`;
hd.innerHTML=`<div class="values">${Object.keys(V).map(v=>`<a href="over.html#${valueId(v)}" class="${location.hash==='#'+valueId(v)?'on':''}">${v}</a>`).join('')}</div><div class="b2"><a class="logo" href="index.html">FEMINEWS</a><nav>${P.map(([f,t])=>`<a href="${f}.html${f==='over'?'#over-ons':''}" class="${f===page?'on':''}">${t}</a>`).join('')}</nav></div>`;
const pad=()=>{if(!hd.classList.contains('s'))document.body.style.paddingTop=hd.offsetHeight+'px'};pad();addEventListener('resize',pad);document.fonts.ready.then(pad);
addEventListener('scroll',()=>{const y=scrollY;if(y>120)hd.classList.add('s');else if(y<30)hd.classList.remove('s')});
$('#foot').innerHTML=`<footer class="wrap"><p><b>Hulp nodig?</b> Veilig Thuis: 0800-2000 (controleer actuele gegevens). Koppen volgen onze stijlgids: dader benoemd, geen eufemismen, geen schuld bij het slachtoffer, en "verdachte" zolang iemand niet is veroordeeld.</p><p class="sm">Prototype voor een studieopdracht: experts, redactie, lezersverhalen en tellingen zijn verzonnen voorbeelddata. <a href="https://mu.social">Volg ons op mu</a></p><button class="exit" onclick="location.replace('https://www.google.nl')">Snel wegklikken</button></footer>`;
/* Kopcheck-regels (Atria, Mulder 2025, Rossetti, UnB) */
const RULES=[[/familiedrama|relatiedrama|liefdesdrama|crime passionnel/i,'Eufemisme: verhult geweld en patroon (Atria).','vrouw gedood door (ex-)partner'],[/steekpartij/i,'Vaag: noem wie wie aanviel en of het partnergeweld was.','poging tot femicide'],[/\b(overleden|om het leven gekomen)\b/i,'Zacht woord: bij geweld is "gedood" duidelijker.','gedood'],[/\b(is|wordt|werd|zijn|worden)\b[^.]*\b(gedood|vermoord|neergestoken|doodgeschoten|mishandeld|verkracht)\b(?!.*\bdoor\b)/i,'Passieve zin zonder dader: wie deed het?',null],[/uit jaloezie|uit liefde|na ruzie|ontrouw|uitdagend|had gedronken/i,'Suggereert (mede)schuld van het slachtoffer (Mulder, 2025).',null],[/psychische problemen|verward/i,'Verschuift aandacht van geweld naar de dader. Alleen gebruiken als relevant.',null]];
function check(t){const flags=[];let fix=t;RULES.forEach(([re,m,r])=>{if(re.test(t)){flags.push(m);if(r)fix=fix.replace(re,r)}});fix=fix.replace(/\bgedood\s+na\s+(?:een\s+)?vrouw\s+gedood\s+door\b/i,'gedood door');return{flags,fix}}
const ci=$('#ci');
if(ci){const run=()=>{const r=check(ci.value);$('#co').innerHTML=!ci.value?'':r.flags.length?`<ul>${r.flags.map(f=>`<li>${f}</li>`).join('')}</ul><p><b>Voorstel:</b> ${r.fix}</p><p class="sm">Gebruik "verdachte" zolang er geen veroordeling is.</p>`:'<p>Geen bezwaren gevonden door onze regels. Lees de kop ook zelf kritisch.</p>'};
 ci.addEventListener('input',run);document.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>{ci.value=b.dataset.ex;run()})}
/* Artikelen (voorbeelddata): titel, categorie, geweld, kleur, vinkje, vrouwelijke bronnen, mannelijke bronnen */
const card=(a,i)=>`<a class="card" href="article.html?id=${i}" style="--c:${a[3]}"><span>${a[0]}</span>${a[4]?'<b title="Kopcheck: getoetst aan de stijlgids">✓</b>':''}</a>`;
if($('#grid'))$('#grid').innerHTML=A.slice(0,7).map(card).join('');
if($('#meter'))$('#meter').innerHTML=`<b>Representatiemeter</b> <a class="meter-info" href="femicide-monitor.html" aria-label="Meer uitleg over de representatiemeter" aria-describedby="meter-help">ⓘ<span class="meter-tooltip" id="meter-help" role="tooltip">Aandeel vrouwelijke bronnen in ons nieuws. 26% is het GMMP-wereldgemiddelde.</span></a><div class="bar"><i style="width:73%">73%</i></div><small>GMMP 2025 wereldgemiddelde: 26%</small>`;
if(page==='article'){const i=+new URLSearchParams(location.search).get('id')||0,a=A[i]||A[0],r=check(a[0]),tot=a[5]+a[6],pc=tot?Math.round(a[5]/tot*100):0;document.title=a[0]+' | FEMINEWS';
 $('#art').innerHTML=`<p class="sm">${a[1]} · Vandaag</p><h1>${a[0]}</h1><div class="hero" style="--c:${a[3]}"></div>
 <p class="sm">${a[4]?'✓ Kop getoetst. ':''}${r.flags.length?'Let op: '+r.flags.join(' '):'Geen bezwaren volgens de Kopcheck.'}</p>
 ${a[7]?a[7].map(t=>`<p>${t}</p>`).join('')+'<p class="sm">Voorbeeldartikel met verzonnen personen.</p>':`<p><i>Voorbeeldtekst:</i> dit prototype toont de opzet van een artikelpagina. Hier komt de volledige tekst, met de dader actief benoemd en het slachtoffer als persoon.</p><p>De redactie vermeldt per artikel wie als bron is gebruikt, zodat lezers zien hoe vrouwen vertegenwoordigd zijn.</p>`}
 <div class="box"><b>Bronnen in dit artikel</b> (voorbeelddata)<div class="bar"><i style="width:${pc}%">${a[5]} vrouw</i></div><small>${a[5]} vrouwelijke en ${a[6]} mannelijke bronnen</small></div>
 ${a[2]?`<div class="help"><b>Context:</b> dit bericht hoort bij een groter patroon. Bekijk de <a href="femicide-monitor.html">Femicide-monitor</a>.<br>Hulp nodig? Veilig Thuis: 0800-2000.</div>`:''}
 <p><a class="btn" href="vrouwen.html">Zoek een vrouwelijke expert</a></p><button onclick="navigator.clipboard.writeText(location.href);this.textContent='Link gekopieerd'">Deel dit artikel</button>
 <h2 class="big">MEER NIEUWS</h2><div class="grid">${A.map((x,j)=>j!==i?card(x,j):'').filter(Boolean).slice(0,3).join('')}</div>`}
/* Monitor */
if($('#chart'))$('#chart').innerHTML=[['Vrouwen als onderwerp, 1995',17],['Vrouwen als onderwerp, 2025',26],['Vrouwelijke verslaggevers, 1995',28],['Vrouwelijke verslaggevers, 2025',41],['Vrouwen in sportnieuws, 2025',15],['Gendergeweld in het nieuws, 2025 (minder dan 2%)',2]].map(([l,v])=>`<div class="row"><span>${l}</span><div class="bar"><i style="width:${v}%">${v}%</i></div></div>`).join('');
/* Over: waarden */
if($('#vals'))$('#vals').innerHTML=Object.entries(V).map(([k,v])=>{const w=WD[k];return `<section class="box value-section" id="${valueId(k)}" style="--value-color:${w[0]}"><h2 class="vt">${k}</h2><p>${w[1]}</p><h3>Wat is er stuk?</h3><p>${w[2]}</p><h3>Zo maken we het waar</h3><div class="value-actions">${w[3].map(([t,x,h])=>`<a class="box" href="${h}"><b>${t}</b><br>${x}<br><span class="tag">Bekijk →</span></a>`).join('')}</div></section>`}).join('');
/* Experts */
if($('#ex')){const d=$('#dlg'),f=$('#filter'),th=[...new Set(E.map(e=>e[3]))];
 f.innerHTML='<option value="">Alle thema\'s</option>'+th.map(t=>`<option>${t}</option>`).join('');
 const t0=new URLSearchParams(location.search).get('t');if(th.includes(t0))f.value=t0;
 const ini=n=>n.split(' ').filter(w=>/^[A-Z]/.test(w)&&!/\.$/.test(w)).map(w=>w[0]).slice(0,2).join('');
 const mail=n=>n.replace(/^(Dr|Prof|Mr)\.\s/,'').toLowerCase().replace(/[^a-z ]/g,'').replace(/ /g,'.')+'@example.org';
 const show=()=>{const q=$('#q').value.toLowerCase(),t=f.value,L=E.map((e,i)=>({e,i})).filter(({e})=>(!t||e[3]===t)&&e.join(' ').toLowerCase().includes(q));
  $('#ex').innerHTML=L.map(({e,i})=>`<a class="box exp" href="#" data-i="${i}"><span class="av">${ini(e[0])}</span><span><b>${e[0]}</b><br>${e[1]}<br><span class="sm">${e[2]} · ${e[3]}</span></span></a>`).join('')||'<p>Geen resultaten.</p>';
  document.querySelectorAll('[data-i]').forEach(a=>a.onclick=ev=>{ev.preventDefault();const e=E[a.dataset.i];d.innerHTML=`<h3>${e[0]}</h3><p>${e[1]}, ${e[2]}</p><p>${e[4]}</p><p><i>“${e[5]}”</i></p><a class="btn" href="mailto:${mail(e[0])}">Neem contact op</a> <button onclick="dlg.close()">Sluiten</button>`;d.showModal()})};
 $('#q').oninput=f.onchange=show;show()}
/* Voorpagina: meer nieuws en expertteaser */
if(page==='index'){$('#grid').insertAdjacentHTML('afterend',`<h2 class="big">MEER NIEUWS</h2>${A.slice(7).map((a,j)=>`<a class="box row2" href="article.html?id=${j+7}"><span><b>${a[0]}</b><br><span class="sm">${a[1]} · ${a[5]} vrouwelijke en ${a[6]} mannelijke bronnen</span></span>${a[4]?'<span class="tag">✓ Kopcheck</span>':''}</a>`).join('')}`);
 $('main').insertAdjacentHTML('beforeend','<div class="box" style="text-align:center;margin-top:2rem"><h2 class="big" style="margin-top:0">EXPERTENZOEKER</h2><p>Zoek een vrouwelijke expert voor jouw verhaal, op thema of naam.</p><a class="btn" href="vrouwen.html">Zoek een vrouwelijke expert</a></div>')}
/* Kopcheck: woordenlijst */
if(page==='kopcheck')$('main').insertAdjacentHTML('beforeend',`<div class="box"><h3>Woorden die we vermijden</h3><table>${[['familiedrama, relatiedrama','vrouw gedood door (ex-)partner'],['steekpartij (bij partnergeweld)','poging tot femicide'],['overleden (bij geweld)','gedood'],['“vrouw werd vermoord”','wie deed het? Noem de verdachte'],['uit jaloezie, na ruzie','weglaten tenzij het ter zake doet'],['dader (vóór een veroordeling)','verdachte']].map(([a,b])=>`<tr><td>${a}</td><td>→ ${b}</td></tr>`).join('')}</table></div>`);
/* Monitor: Kopcheck-resultaten (voorbeeld) */
if(page==='femicide-monitor')$('main').insertAdjacentHTML('beforeend',`<div class="box"><h3>Kopcheck op ons eigen platform (voorbeeld)</h3>${[['Koppen getoetst',128,128],['Koppen aangepast',31,128],['Eufemisme gevonden',14,31],['Passieve zin gevonden',11,31],['Schuld-frame gevonden',6,31]].map(([l,v,m])=>`<div class="row"><span>${l}</span><div class="bar"><i style="width:${v/m*100}%">${v}</i></div></div>`).join('')}<p class="sm">Verzonnen voorbeeldtellingen.</p></div>`);
/* Over: redactie en mu */
if($('#team'))$('#team').innerHTML=[['Sanne de Wit','Hoofdredacteur'],['Naima Haddou','Eindredacteur Kopcheck'],['Fleur Jansen','Verslaggever recht en geweld'],['Yara Postma','Community en experts']].map(([n,r])=>`<div class="box exp"><span class="av">${n.split(' ').map(w=>w[0]).join('')}</span><span><b>${n}</b><br>${r}</span></div>`).join('');
/* Community */
const cf=$('#cf');
if(cf){const K='fn_kopen',get=()=>{try{return JSON.parse(localStorage[K]||'[]')}catch(e){return[]}},seed=['Vrouw (29) overleden na familiedrama in Zwolle','Man (41) steekt ex neer uit jaloezie','Vrouw wordt doodgestoken in woning'].map(t=>[t,check(t).fix]),
 draw=()=>$('#cl').innerHTML=get().concat(seed).filter(([a,b])=>a!==b).map(([a,b])=>`<div class="box ba"><div>${a}</div><em>→</em><div>${b}</div></div>`).join('');
 cf.onsubmit=e=>{e.preventDefault();const v=cf.kop.value.trim();if(!v)return;const l=get();l.unshift([v,check(v).fix]);try{localStorage[K]=JSON.stringify(l)}catch(x){}draw();cf.reset()};draw();
 const S=[['Anoniem','Eindelijk een kop die het zegt zoals het is','Toen ik las over “een drama in huis” voelde het alsof niemand de dader durfde te noemen. Hier staat gewoon wat er gebeurd is.',24],['Mila, 32','Een vrouwelijke expert gevonden in vijf minuten','Via de expertenzoeker vond ik een hoogleraar voor mijn podcast die ik anders nooit had gekend.',17],['Anoniem','Wat ik wil dat mensen weten over hulp','Het hielp mij te lezen dat ik niet de enige was. Praat met Veilig Thuis of iemand die je vertrouwt.',41]];
 const stories=$('#stories'),RK='fn_story_replies';
 const replies=()=>{try{const v=JSON.parse(localStorage.getItem(RK)||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}catch(e){return{}}};
 const renderReplies=(list,items)=>{list.replaceChildren();items.forEach(({name,text})=>{const row=document.createElement('div'),author=document.createElement('b'),body=document.createElement('p');row.className='story-reply';author.textContent=name;body.textContent=text;row.append(author,body);list.append(row)})};
 stories.innerHTML=S.map(([n,t,x,l],i)=>`<article class="box story-card" data-story="${i}"><b>${t}</b> <span class="sm">${n}</span><p>${x}</p><button type="button" data-l="${l}">♥ <span>${l}</span></button><div class="story-replies" aria-live="polite"></div><form class="reply-form" data-reply-form="${i}"><label><span class="sm">Jouw reactie</span><textarea name="reply" rows="2" maxlength="500" required placeholder="Schrijf een respectvolle reactie (max. 500 tekens)"></textarea></label><div class="reply-controls"><label class="reply-anon"><input type="checkbox" name="anonymous" checked> Anoniem reageren</label><label class="reply-name">Naam <input name="name" maxlength="40" placeholder="Bijvoorbeeld: Noor" disabled></label><button type="submit">Plaats reactie</button></div></form></article>`).join('');
 const saved=replies();S.forEach((_,i)=>renderReplies(stories.querySelector(`[data-story="${i}"] .story-replies`),Array.isArray(saved[i])?saved[i]:[]));
 stories.addEventListener('change',e=>{if(e.target.matches('input[name="anonymous"]')){const name=e.target.closest('form').elements.name;name.disabled=e.target.checked;name.required=!e.target.checked;if(e.target.checked)name.value=''}});
 stories.addEventListener('submit',e=>{const form=e.target.closest('[data-reply-form]');if(!form)return;e.preventDefault();const text=form.elements.reply.value.trim(),anonymous=form.elements.anonymous.checked,name=anonymous?'Anoniem':form.elements.name.value.trim();if(!text||(!anonymous&&!name))return;const all=replies(),id=form.dataset.replyForm,list=Array.isArray(all[id])?all[id]:[];list.push({name,text});all[id]=list;try{localStorage.setItem(RK,JSON.stringify(all))}catch(error){alert('Je reactie kon niet worden opgeslagen. Controleer de opslagruimte van je browser en probeer het opnieuw.');return}renderReplies(stories.querySelector(`[data-story="${id}"] .story-replies`),list);form.reset();form.elements.name.disabled=true});
 document.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>{const s=b.querySelector('span');s.textContent=+s.textContent+(b.dataset.on?-1:1);b.dataset.on=b.dataset.on?'':'1'})}

/* Waardepagina */
if(page==='waarde'){const ks=Object.keys(V),q=new URLSearchParams(location.search).get('w'),key=WD[q]?q:ks[0],w=WD[key],i=ks.indexOf(key),pv=ks[(i+3)%4],nx=ks[(i+1)%4];document.title=key+' | FEMINEWS';
 $('#wd').innerHTML=`<div class="box" style="background:${w[0]}"><h1 class="vt">${key}</h1><p>${w[1]}</p></div><div class="box"><h3>Wat is er stuk?</h3><p>${w[2]}</p></div><h3>Zo maken we het waar</h3><div class="cols">${w[3].map(([t,x,h])=>`<a class="box" href="${h}" style="text-decoration:none"><b>${t}</b><br>${x}<br><span class="tag">Bekijk →</span></a>`).join('')}</div><p class="nav2"><a class="btn" href="waarde.html?w=${pv}">← ${pv}</a><a class="btn" href="over.html">Over ons</a><a class="btn" href="waarde.html?w=${nx}">${nx} →</a></p>`}
