/* Voorbeelddata: de eerste 7 artikelen komen uit het ontwerp (zonder echte artikeltekst); de rest en alle personen zijn verzonnen.
   Artikel: [titel, categorie, geweld, kleur, vinkje, vrouwelijke bronnen, mannelijke bronnen, tekst] */
const A=[['Oud-studente van Cornell bedreigd na aanklacht over groepsverkrachting op campus','Wereld',1,'#6b7f5e',1,3,1],['Onderzoek naar fataal auto-ongeluk vrouw op Aruba, familie betwijfelt toedracht','Onderzoek',1,'#a0714f',1,2,2],['Cel- en taakstraf voor tegenstanders azc Engelen die vrouw mishandelden','Justitie',1,'#5b6b8c',1,2,3],['Minister Berendsen: contact met vermiste Nederlandse in Nepal','Politiek',0,'#7c6a55',1,2,2],['Elfde dode vrouw gevonden in Johannesburg, zorgen over seriemoordenaar','Wereld',1,'#4f6b8a',1,1,3],['Opnieuw dode vrouw gevonden bij Johannesburg, nu al tien','Wereld',1,'#8a5a5a',1,1,2],["Koeman 'diep geraakt' door alle steunbetuigingen na overlijden vrouw",'Sport',0,'#8a2f2f',0,0,2],
['Nieuw onderzoeksproject moet hartklachten bij vrouwen sneller herkennen','Wetenschap',0,'#5b7f8c',1,3,1,['Een onderzoeksteam start een driejarig project om te achterhalen waarom hartklachten bij vrouwen vaak later worden herkend. Huisartsen en ziekenhuizen doen mee.','“We willen dat de signalen bij vrouwen net zo snel worden herkend als bij mannen,” zegt onderzoeker dr. Mirthe van Rooijen.']],
['Man (44) aangehouden na dood van vrouw in Zwolle, verdachte is haar ex-partner','Justitie',1,'#6a5b8c',1,2,2,['De politie heeft een 44-jarige man aangehouden op verdenking van het doden van zijn ex-partner. De vrouw (38) werd dinsdagavond dood gevonden in haar woning.','Wie het geweld heeft gepleegd, noemen we in de kop. Meer cijfers over femicide staan in onze monitor.']],
['Eerste vrouwelijke hoofdtrainer bij lokale voetbalclub: ‘Talent kent geen geslacht’','Sport',0,'#4f8a5b',1,2,1,['Een amateurclub heeft voor het eerst een vrouw als hoofdtrainer van het eerste herenteam aangesteld. De spelers reageerden enthousiast.','Sportpsycholoog Joyce Hendriks ziet het als een belangrijk signaal: “Rolmodellen op de trainersbank maken het voor meisjes normaler om door te groeien.”']],
['Gemeente verdubbelt budget voor vrouwenopvang na stijging van meldingen','Politiek',1,'#8a6a4f',1,2,2,['De gemeenteraad heeft ingestemd met een verdubbeling van het budget voor opvang van vrouwen die huiselijk geweld meemaken.','Raadslid Eva de Graaf: “Wie veilig weg wil, mag niet op een wachtlijst belanden.”']],
['Loonkloof wordt kleiner, maar blijft groot voor vrouwen met kinderen','Economie',0,'#8a7f4f',1,2,2,['Nieuwe cijfers laten zien dat het verschil in uurloon tussen mannen en vrouwen krimpt, maar dat vrouwen met kinderen nog altijd het meeste achterblijven.','Econoom Noor Bakker pleit voor betaalbare kinderopvang en gelijke verdeling van zorgverlof.']],
['Schrijfster wint literatuurprijs met debuut over drie generaties vrouwen','Cultuur',0,'#8a4f6a',1,3,1,['Het debuut vertelt het verhaal van een grootmoeder, moeder en dochter in drie decennia. De jury noemt het boek “zacht en scherp tegelijk”.','Literatuurcriticus Zeynep Aydin prijst vooral de stem van de personages.']],
['Lokale omroep geeft vrouwelijke experts voortaan meer zendtijd','Media',0,'#4f6b8a',1,3,1,['Een lokale omroep heeft afgesproken dat in elk programma minstens de helft van de gasten die als expert optreden een vrouw is.','Hoofdredacteur Marijke Kuipers: “We hadden de namen gewoon niet bij de hand. Nu wel.”']]];
/* Experts: [naam, functie, organisatie, thema, bio, quote] (allemaal verzonnen) */
const E=[['Dr. Mirthe van Rooijen','Onderzoeker cardiologie','Universitair medisch centrum','Zorg','Onderzoekt verschillen tussen mannen en vrouwen in hartzorg.','Goede zorg begint met goed luisteren.'],
['Prof. Aisha El Idrissi','Hoogleraar strafrecht','Universiteit','Recht','Specialiseert zich in geweld binnen relaties en slachtofferrechten.','Recht moet ook veiligheid voor slachtoffers betekenen.'],
['Mr. Lotte Brouwer','Advocaat familierecht','Advocatenkantoor','Recht','Staat vrouwen bij in omgangs- en gezagszaken na geweld.','Veiligheid gaat voor omgang.'],
['Dr. Femke Smit','Onderzoeker huiselijk geweld','Kenniscentrum','Zorg','Onderzoekt voortekenen van partnergeweld en hulpverlening.','Patronen zijn te herkennen, als je ernaar zoekt.'],
['Noor Bakker','Econoom arbeidsmarkt','Onderzoeksbureau','Economie','Analyseert loonkloof en deeltijdwerk.','Cijfers laten zien wat verhalen al zeiden.'],
['Prof. Ingrid Vos','Hoogleraar gendereconomie','Universiteit','Economie','Schrijft over onbetaalde zorg en de economie.','Zorg is werk, ook als er geen loon tegenover staat.'],
['Dr. Sofia Marques','Klimaatwetenschapper','Onderzoeksinstituut','Wetenschap','Werkt aan klimaatmodellen voor kustgebieden.','Goede modellen redden land en levens.'],
['Dr. Yasmin Kaya','Datawetenschapper','Hogeschool','Wetenschap','Onderzoekt vooroordelen in algoritmen en taalmodellen.','Data zijn nooit neutraal.'],
['Eva de Graaf','Raadslid en beleidsadviseur','Gemeente','Politiek','Zet zich in voor opvang en preventie in de gemeente.','Beleid is pas goed als het bij mensen aankomt.'],
['Joyce Hendriks','Sportpsycholoog','Sportbond','Sport','Begeleidt jonge sporters en coaches.','Wie het kan zien, kan het worden.'],
['Zeynep Aydin','Literatuurcriticus','Cultureel tijdschrift','Cultuur','Recenseert hedendaagse literatuur en bespreekt vrouwelijke schrijvers.','Een stem horen is een stem geloven.'],
['Marijke Kuipers','Hoofdredacteur','Lokale omroep','Media','Werkt aan gelijke verdeling van bronnen in de redactie.','Wie je niet vraagt, hoor je niet.']];
/* Waarden: [kleur, uitleg, wat is er stuk, [[onderdeel, uitleg, link]]] */
const WD={
Solidariteit:['#d9c8f5','Vrouwen en hun verhalen staan centraal. Onze berichtgeving verbindt individuele gevallen met elkaar en met een gemeenschap van lezers, makers en organisaties.','Zaken worden als losse incidenten gebracht, waardoor lezers geen gedeeld probleem zien (Atria).',[['Community','Lezers sturen koppen in en delen verhalen.','community.html'],['Femicide-monitor','We plaatsen losse zaken in een patroon.','femicide-monitor.html'],['Open kanalen','Je volgt ons via mu social of het Fediverse, zonder Big Tech.','https://mu.social']]],
Veiligheid:['#bfe0f5','Onze berichtgeving over geweld is zorgvuldig, bevat hulpinformatie en maakt patronen zichtbaar, zodat risico’s herkend worden.','Patronen en voortekens van geweld blijven onbenoemd en slechts 33% van de Nederlanders kende in 2022 het begrip femicide.',[['Hulpblok','Bij elk artikel over geweld staat hulpinformatie.','article.html?id=8'],['Snel wegklikken','Op elke pagina kun je in één klik weg, voor een onveilige thuissituatie.','index.html'],['Femicide-monitor','Cijfers en patronen, zodat risico’s herkenbaar worden.','femicide-monitor.html']]],
Rechtvaardigheid:['#ffb3de','Onze koppen en artikelen leggen verantwoordelijkheid bij de dader, niet bij het slachtoffer. Vrouwen krijgen een eerlijk aandeel in nieuws en expertise.','Passieve koppen, eufemismen en victim-blaming verschuiven de verantwoordelijkheid van dader naar slachtoffer.',[['Kopcheck','Elke kop wordt getoetst aan onze stijlgids.','kopcheck.html'],['Woordenlijst','Welke woorden we vermijden en wat we in plaats daarvan schrijven.','kopcheck.html'],['Representatiemeter','We laten zien hoeveel vrouwen als bron voorkomen.','index.html']]],
Empowerment:['#ffd9a8','Wij tonen vrouwen als experts, leiders en makers, niet alleen als slachtoffer. Lezers krijgen taal en kennis om geweld te herkennen en te benoemen.','Vrouwen zijn zeldzaam als bron en expert: slechts 26% van de mensen in het nieuws is vrouw (GMMP 2025).',[['Expertenzoeker','Journalisten vinden direct een vrouwelijke expert.','vrouwen.html'],['Bronnen per artikel','Bij elk artikel zie je hoeveel vrouwelijke bronnen we gebruikten.','article.html?id=7'],['Onze redactie','Vrouwen maken het nieuws.','over.html']]]};
